//
// Generated by JTB 1.2.2
//

package parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> CompilationUnit()
 * f1 -> ";"
 */
public class CompilationStatement implements Node {
   private Node parent;
   public CompilationUnit f0;
   public NodeToken f1;

   public CompilationStatement(CompilationUnit n0, NodeToken n1) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
      f1 = n1;
      if ( f1 != null ) f1.setParent(this);
   }

   public CompilationStatement(CompilationUnit n0) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
      f1 = new NodeToken(";");
      if ( f1 != null ) f1.setParent(this);
   }

   public void accept(parser.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(parser.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

